"""
Error codes for ClustR application.
"""

class CommonAPIErrorCodes:
    """
    Common API error codes used across the application.
    """
    # Authentication and Authorization
    AUTHENTICATION_ERROR = "AUTHENTICATION_ERROR"
    AUTHORIZATION_ERROR = "AUTHORIZATION_ERROR"
    PERMISSION_DENIED = "PERMISSION_DENIED"
    
    # Resource errors
    RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND"
    RESOURCE_CONFLICT = "RESOURCE_CONFLICT"
    DUPLICATE_ENTITY = "DUPLICATE_ENTITY"
    
    # Validation errors
    VALIDATION_ERROR = "VALIDATION_ERROR"
    INVALID_INPUT = "INVALID_INPUT"
    MISSING_REQUIRED_FIELD = "MISSING_REQUIRED_FIELD"
    
    # Payment errors
    PAYMENT_ERROR = "PAYMENT_ERROR"
    INSUFFICIENT_FUNDS = "INSUFFICIENT_FUNDS"
    PAYMENT_GATEWAY_ERROR = "PAYMENT_GATEWAY_ERROR"
    
    # External service errors
    EXTERNAL_SERVICE_ERROR = "EXTERNAL_SERVICE_ERROR"
    SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE"
    
    # Cluster errors
    CLUSTER_ACCESS_DENIED = "CLUSTER_ACCESS_DENIED"
    CLUSTER_NOT_FOUND = "CLUSTER_NOT_FOUND"
    
    # Rate limiting
    RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED"
    
    # Server errors
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
    DATABASE_ERROR = "DATABASE_ERROR"
    
    # File errors
    FILE_UPLOAD_ERROR = "FILE_UPLOAD_ERROR"
    FILE_SIZE_EXCEEDED = "FILE_SIZE_EXCEEDED"
    INVALID_FILE_TYPE = "INVALID_FILE_TYPE"
    
    # Business logic errors
    BUSINESS_LOGIC_ERROR = "BUSINESS_LOGIC_ERROR"
    OPERATION_NOT_ALLOWED = "OPERATION_NOT_ALLOWED"
    FEATURE_DISABLED = "FEATURE_DISABLED"