# Generated by Django 4.2.9 on 2024-08-11 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClusterUnit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="UUID primary key",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="creation date")),
                (
                    "created_by",
                    models.UUIDField(
                        editable=False,
                        help_text="the Id of the ClustR account user who added this object.",
                        null=True,
                        verbose_name="created by",
                    ),
                ),
                ("last_modified_at", models.DateTimeField(auto_now=True, verbose_name="last modified date")),
                (
                    "last_modified_by",
                    models.UUIDField(
                        editable=False,
                        help_text="the Id of the ClustR account user who last modified this object.",
                        null=True,
                        verbose_name="last modified by",
                    ),
                ),
                ("name", models.CharField(help_text="Cluster unit name", max_length=255, verbose_name="Name")),
                (
                    "unique_number",
                    models.CharField(
                        help_text="Cluster unit unique number", max_length=255, verbose_name="Unique Number"
                    ),
                ),
                ("address", models.JSONField(help_text="Cluster unit address", verbose_name="Address")),
                ("type", models.CharField(help_text="Cluster unit type", max_length=255, verbose_name="Type")),
                ("status", models.CharField(help_text="Cluster unit status", max_length=255, verbose_name="Status")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserConfiguration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="UUID primary key",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="creation date")),
                (
                    "created_by",
                    models.UUIDField(
                        editable=False,
                        help_text="the Id of the ClustR account user who added this object.",
                        null=True,
                        verbose_name="created by",
                    ),
                ),
                ("last_modified_at", models.DateTimeField(auto_now=True, verbose_name="last modified date")),
                (
                    "last_modified_by",
                    models.UUIDField(
                        editable=False,
                        help_text="the Id of the ClustR account user who last modified this object.",
                        null=True,
                        verbose_name="last modified by",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Comments",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="UUID primary key",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="creation date")),
                (
                    "created_by",
                    models.UUIDField(
                        editable=False,
                        help_text="the Id of the ClustR account user who added this object.",
                        null=True,
                        verbose_name="created by",
                    ),
                ),
                ("last_modified_at", models.DateTimeField(auto_now=True, verbose_name="last modified date")),
                (
                    "last_modified_by",
                    models.UUIDField(
                        editable=False,
                        help_text="the Id of the ClustR account user who last modified this object.",
                        null=True,
                        verbose_name="last modified by",
                    ),
                ),
                ("text", models.TextField(help_text="Comment text", verbose_name="Text")),
                ("object_id", models.UUIDField()),
                (
                    "content_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Cluster",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="UUID primary key",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="creation date")),
                (
                    "created_by",
                    models.UUIDField(
                        editable=False,
                        help_text="the Id of the ClustR account user who added this object.",
                        null=True,
                        verbose_name="created by",
                    ),
                ),
                ("last_modified_at", models.DateTimeField(auto_now=True, verbose_name="last modified date")),
                (
                    "last_modified_by",
                    models.UUIDField(
                        editable=False,
                        help_text="the Id of the ClustR account user who last modified this object.",
                        null=True,
                        verbose_name="last modified by",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("ESTATE", "Estate"), ("FACILITY", "Facility")],
                        help_text="Cluster type",
                        max_length=255,
                        verbose_name="Type",
                    ),
                ),
                ("name", models.CharField(help_text="Cluster name", max_length=255, unique=True, verbose_name="Name")),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="The Description for the Cluster", verbose_name="Description"
                    ),
                ),
                (
                    "tenant_subdomain",
                    models.URLField(
                        help_text="The subdomain assigned to this particular cluster",
                        unique=True,
                        verbose_name="Tenant Subdomain",
                    ),
                ),
                (
                    "admin",
                    models.OneToOneField(
                        help_text="The admin for this cluster",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cluster_admin",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Assets",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="UUID primary key",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="creation date")),
                (
                    "created_by",
                    models.UUIDField(
                        editable=False,
                        help_text="the Id of the ClustR account user who added this object.",
                        null=True,
                        verbose_name="created by",
                    ),
                ),
                ("last_modified_at", models.DateTimeField(auto_now=True, verbose_name="last modified date")),
                (
                    "last_modified_by",
                    models.UUIDField(
                        editable=False,
                        help_text="the Id of the ClustR account user who last modified this object.",
                        null=True,
                        verbose_name="last modified by",
                    ),
                ),
                ("resource_url", models.URLField(help_text="URL of asset resource", verbose_name="Resource URL")),
                ("type", models.CharField(help_text="Asset type", max_length=255, verbose_name="Type")),
                ("object_id", models.UUIDField()),
                (
                    "content_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
