# Generated by Django 4.2.9 on 2024-08-17 06:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cluster",
            name="tenant_subdomain",
        ),
        migrations.AddField(
            model_name="cluster",
            name="address",
            field=models.JSONField(
                default=None,
                help_text="The address of the Cluster: (Facility or Estate)",
                null=True,
                verbose_name="Address",
            ),
        ),
    ]
