# Generated by Django 5.2.4 on 2025-07-31 08:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_add_bill_dispute_model"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="announcement",
            options={
                "default_permissions": [],
                "ordering": ["-published_at", "-created_at"],
                "verbose_name": "announcement",
                "verbose_name_plural": "announcements",
            },
        ),
        migrations.AlterModelOptions(
            name="announcementattachment",
            options={
                "default_permissions": [],
                "ordering": ["created_at"],
                "verbose_name": "announcement attachment",
                "verbose_name_plural": "announcement attachments",
            },
        ),
        migrations.AlterModelOptions(
            name="announcementcomment",
            options={
                "default_permissions": [],
                "ordering": ["-created_at"],
                "verbose_name": "announcement comment",
                "verbose_name_plural": "announcement comments",
            },
        ),
        migrations.AlterModelOptions(
            name="announcementlike",
            options={
                "default_permissions": [],
                "verbose_name": "announcement like",
                "verbose_name_plural": "announcement likes",
            },
        ),
        migrations.AlterModelOptions(
            name="announcementreadstatus",
            options={
                "default_permissions": [],
                "verbose_name": "announcement read status",
                "verbose_name_plural": "announcement read statuses",
            },
        ),
        migrations.AlterModelOptions(
            name="announcementview",
            options={
                "default_permissions": [],
                "verbose_name": "announcement view",
                "verbose_name_plural": "announcement views",
            },
        ),
        migrations.AlterModelOptions(
            name="bill",
            options={
                "default_permissions": [],
                "ordering": ["-created_at"],
                "verbose_name": "Bill",
                "verbose_name_plural": "Bills",
            },
        ),
        migrations.AlterModelOptions(
            name="child",
            options={
                "default_permissions": [],
                "ordering": ["name"],
                "verbose_name": "Child",
                "verbose_name_plural": "Children",
            },
        ),
        migrations.AlterModelOptions(
            name="cluster",
            options={
                "default_permissions": [],
                "ordering": ["name"],
                "verbose_name": "cluster",
                "verbose_name_plural": "clusters",
            },
        ),
        migrations.AlterModelOptions(
            name="emergencycontact",
            options={
                "default_permissions": [],
                "ordering": ["-is_primary", "name"],
                "verbose_name": "Emergency Contact",
                "verbose_name_plural": "Emergency Contacts",
            },
        ),
        migrations.AlterModelOptions(
            name="emergencyresponse",
            options={
                "default_permissions": [],
                "ordering": ["-created_at"],
                "verbose_name": "Emergency Response",
                "verbose_name_plural": "Emergency Responses",
            },
        ),
        migrations.AlterModelOptions(
            name="entryexitlog",
            options={
                "default_permissions": [],
                "ordering": ["-date", "-exit_time"],
                "verbose_name": "Entry/Exit Log",
                "verbose_name_plural": "Entry/Exit Logs",
            },
        ),
        migrations.AlterModelOptions(
            name="event",
            options={
                "default_permissions": [],
                "ordering": ["-event_date", "-event_time"],
                "verbose_name": "event",
                "verbose_name_plural": "events",
            },
        ),
        migrations.AlterModelOptions(
            name="eventguest",
            options={
                "default_permissions": [],
                "ordering": ["name"],
                "verbose_name": "event guest",
                "verbose_name_plural": "event guests",
            },
        ),
        migrations.AlterModelOptions(
            name="exitrequest",
            options={
                "default_permissions": [],
                "ordering": ["-created_at"],
                "verbose_name": "Exit Request",
                "verbose_name_plural": "Exit Requests",
            },
        ),
        migrations.AlterModelOptions(
            name="invitation",
            options={
                "default_permissions": [],
                "ordering": ["-start_date", "status"],
                "verbose_name": "invitation",
                "verbose_name_plural": "invitations",
            },
        ),
        migrations.AlterModelOptions(
            name="issueattachment",
            options={
                "default_permissions": [],
                "ordering": ["created_at"],
                "verbose_name": "issue attachment",
                "verbose_name_plural": "issue attachments",
            },
        ),
        migrations.AlterModelOptions(
            name="issuecomment",
            options={
                "default_permissions": [],
                "ordering": ["created_at"],
                "verbose_name": "issue comment",
                "verbose_name_plural": "issue comments",
            },
        ),
        migrations.AlterModelOptions(
            name="issuestatushistory",
            options={
                "default_permissions": [],
                "ordering": ["-created_at"],
                "verbose_name": "issue status history",
                "verbose_name_plural": "issue status histories",
            },
        ),
        migrations.AlterModelOptions(
            name="issueticket",
            options={
                "default_permissions": [],
                "ordering": ["-created_at"],
                "verbose_name": "issue ticket",
                "verbose_name_plural": "issue tickets",
            },
        ),
        migrations.AlterModelOptions(
            name="maintenanceattachment",
            options={
                "default_permissions": [],
                "ordering": ["created_at"],
                "verbose_name": "maintenance attachment",
                "verbose_name_plural": "maintenance attachments",
            },
        ),
        migrations.AlterModelOptions(
            name="maintenancecomment",
            options={
                "default_permissions": [],
                "ordering": ["created_at"],
                "verbose_name": "maintenance comment",
                "verbose_name_plural": "maintenance comments",
            },
        ),
        migrations.AlterModelOptions(
            name="maintenancecost",
            options={
                "default_permissions": [],
                "ordering": ["date_incurred"],
                "verbose_name": "maintenance cost",
                "verbose_name_plural": "maintenance costs",
            },
        ),
        migrations.AlterModelOptions(
            name="maintenancelog",
            options={
                "default_permissions": [],
                "ordering": ["-created_at"],
                "verbose_name": "maintenance log",
                "verbose_name_plural": "maintenance logs",
            },
        ),
        migrations.AlterModelOptions(
            name="maintenanceschedule",
            options={
                "default_permissions": [],
                "ordering": ["next_due_date"],
                "verbose_name": "maintenance schedule",
                "verbose_name_plural": "maintenance schedules",
            },
        ),
        migrations.AlterModelOptions(
            name="paymenterror",
            options={
                "default_permissions": [],
                "ordering": ["-created_at"],
                "verbose_name": "Payment Error",
                "verbose_name_plural": "Payment Errors",
            },
        ),
        migrations.AlterModelOptions(
            name="recurringpayment",
            options={
                "default_permissions": [],
                "ordering": ["-created_at"],
                "verbose_name": "Recurring Payment",
                "verbose_name_plural": "Recurring Payments",
            },
        ),
        migrations.AlterModelOptions(
            name="shift",
            options={
                "default_permissions": [],
                "ordering": ["-start_time"],
                "verbose_name": "shift",
                "verbose_name_plural": "shifts",
            },
        ),
        migrations.AlterModelOptions(
            name="shiftattendance",
            options={
                "default_permissions": [],
                "verbose_name": "shift attendance",
                "verbose_name_plural": "shift attendances",
            },
        ),
        migrations.AlterModelOptions(
            name="shiftswaprequest",
            options={
                "default_permissions": [],
                "ordering": ["-created_at"],
                "verbose_name": "shift swap request",
                "verbose_name_plural": "shift swap requests",
            },
        ),
        migrations.AlterModelOptions(
            name="sosalert",
            options={
                "default_permissions": [],
                "ordering": ["-created_at"],
                "verbose_name": "SOS Alert",
                "verbose_name_plural": "SOS Alerts",
            },
        ),
        migrations.AlterModelOptions(
            name="task",
            options={
                "default_permissions": [],
                "ordering": ["-created_at"],
                "verbose_name": "task",
                "verbose_name_plural": "tasks",
            },
        ),
        migrations.AlterModelOptions(
            name="taskassignment",
            options={
                "default_permissions": [],
                "ordering": ["-assigned_at"],
                "verbose_name": "task assignment",
                "verbose_name_plural": "task assignments",
            },
        ),
        migrations.AlterModelOptions(
            name="taskassignmenthistory",
            options={
                "default_permissions": [],
                "ordering": ["-created_at"],
                "verbose_name": "task assignment history",
                "verbose_name_plural": "task assignment histories",
            },
        ),
        migrations.AlterModelOptions(
            name="taskattachment",
            options={
                "default_permissions": [],
                "ordering": ["created_at"],
                "verbose_name": "task attachment",
                "verbose_name_plural": "task attachments",
            },
        ),
        migrations.AlterModelOptions(
            name="taskcomment",
            options={
                "default_permissions": [],
                "ordering": ["created_at"],
                "verbose_name": "task comment",
                "verbose_name_plural": "task comments",
            },
        ),
        migrations.AlterModelOptions(
            name="taskescalationhistory",
            options={
                "default_permissions": [],
                "ordering": ["-created_at"],
                "verbose_name": "task escalation history",
                "verbose_name_plural": "task escalation histories",
            },
        ),
        migrations.AlterModelOptions(
            name="taskstatushistory",
            options={
                "default_permissions": [],
                "ordering": ["-created_at"],
                "verbose_name": "task status history",
                "verbose_name_plural": "task status histories",
            },
        ),
        migrations.AlterModelOptions(
            name="transaction",
            options={
                "default_permissions": [],
                "ordering": ["-created_at"],
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
            },
        ),
        migrations.AlterModelOptions(
            name="utilityprovider",
            options={
                "default_permissions": [],
                "verbose_name": "Utility Provider",
                "verbose_name_plural": "Utility Providers",
            },
        ),
        migrations.AlterModelOptions(
            name="visitor",
            options={
                "default_permissions": [],
                "ordering": ["-estimated_arrival"],
                "verbose_name": "visitor",
                "verbose_name_plural": "visitors",
            },
        ),
        migrations.AlterModelOptions(
            name="visitorlog",
            options={
                "default_permissions": [],
                "ordering": ["-date", "-arrival_time"],
                "verbose_name": "visitor log",
                "verbose_name_plural": "visitor logs",
            },
        ),
        migrations.AlterModelOptions(
            name="wallet",
            options={
                "default_permissions": [],
                "verbose_name": "Wallet",
                "verbose_name_plural": "Wallets",
            },
        ),
        migrations.RemoveIndex(
            model_name="announcement",
            name="common_anno_cluster_1c0671_idx",
        ),
        migrations.RemoveIndex(
            model_name="announcement",
            name="common_anno_cluster_2c6b45_idx",
        ),
        migrations.RemoveIndex(
            model_name="announcementattachment",
            name="common_anno_is_imag_26e67f_idx",
        ),
        migrations.RemoveIndex(
            model_name="announcementlike",
            name="common_anno_announc_5eaeb8_idx",
        ),
        migrations.RemoveIndex(
            model_name="announcementreadstatus",
            name="common_anno_user_id_001b98_idx",
        ),
        migrations.RemoveIndex(
            model_name="announcementreadstatus",
            name="common_anno_announc_f19ab1_idx",
        ),
        migrations.RemoveIndex(
            model_name="announcementview",
            name="common_anno_announc_e1bfa3_idx",
        ),
        migrations.RemoveIndex(
            model_name="bill",
            name="common_bill_user_id_de260e_idx",
        ),
        migrations.RenameIndex(
            model_name="billdispute",
            new_name="common_bill_cluster_0adca2_idx",
            old_name="common_billdispute_cluster_bill_idx",
        ),
        migrations.RenameIndex(
            model_name="billdispute",
            new_name="common_bill_dispute_2c38b1_idx",
            old_name="common_billdispute_disputed_by_idx",
        ),
        migrations.RenameIndex(
            model_name="billdispute",
            new_name="common_bill_status_a00ce5_idx",
            old_name="common_billdispute_status_idx",
        ),
        migrations.RenameIndex(
            model_name="billdispute",
            new_name="common_bill_created_eaa983_idx",
            old_name="common_billdispute_created_at_idx",
        ),
        migrations.RenameIndex(
            model_name="billdispute",
            new_name="common_bill_resolve_bcc2e6_idx",
            old_name="common_billdispute_resolved_at_idx",
        ),
        migrations.AddField(
            model_name="bill",
            name="created_by_user",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if the bill was created by the user themselves, not an admin.",
            ),
        ),
        migrations.AddField(
            model_name="billdispute",
            name="created_by",
            field=models.UUIDField(
                help_text="the Id of the ClustR account user who added this object.",
                null=True,
                verbose_name="created by",
            ),
        ),
        migrations.AddField(
            model_name="billdispute",
            name="last_modified_by",
            field=models.UUIDField(
                help_text="the Id of the ClustR account user who last modified this object.",
                null=True,
                verbose_name="last modified by",
            ),
        ),
        migrations.AlterField(
            model_name="billdispute",
            name="cluster",
            field=models.ForeignKey(
                help_text="The cluster this object belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                related_query_name="%(class)s",
                to="common.cluster",
                verbose_name="cluster",
            ),
        ),
        migrations.AlterField(
            model_name="billdispute",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="creation date"),
        ),
        migrations.AlterField(
            model_name="billdispute",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                help_text="UUID primary key",
                primary_key=True,
                serialize=False,
                verbose_name="id",
            ),
        ),
        migrations.AlterField(
            model_name="billdispute",
            name="last_modified_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="last modified date"
            ),
        ),
        migrations.AddIndex(
            model_name="announcement",
            index=models.Index(
                condition=models.Q(("is_published", True)),
                fields=["cluster", "published_at"],
                name="published_announcement_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="announcementattachment",
            index=models.Index(
                condition=models.Q(("is_image", True)),
                fields=["announcement"],
                name="image_attachment_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="announcementreadstatus",
            index=models.Index(
                condition=models.Q(("is_read", True)),
                fields=["user_id"],
                name="read_announcement_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="announcementreadstatus",
            index=models.Index(
                condition=models.Q(("is_read", False)),
                fields=["user_id"],
                name="unread_announcement_idx",
            ),
        ),
    ]
