# Generated by Django 4.2.9 on 2024-08-22 04:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("common", "0002_remove_cluster_tenant_subdomain_cluster_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cluster",
            name="admin",
            field=models.OneToOneField(
                help_text="The admin for this cluster",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="admin_cluster",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
