# Generated by Django 5.2.4 on 2025-08-12 09:49

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0003_alter_announcement_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="idempotency_key",
            field=models.CharField(
                blank=True,
                help_text="Unique key to prevent duplicate transactions",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="idempotency key",
            ),
        ),
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creation date"
                    ),
                ),
                (
                    "created_by",
                    models.UUIDField(
                        help_text="the Id of the ClustR account user who added this object.",
                        null=True,
                        verbose_name="created by",
                    ),
                ),
                (
                    "last_modified_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="last modified date"
                    ),
                ),
                (
                    "last_modified_by",
                    models.UUIDField(
                        help_text="the Id of the ClustR account user who last modified this object.",
                        null=True,
                        verbose_name="last modified by",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="UUID primary key",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "chat_type",
                    models.CharField(
                        choices=[("INDIVIDUAL", "Individual"), ("GROUP", "Group")],
                        default="INDIVIDUAL",
                        help_text="Type of chat conversation",
                        max_length=20,
                        verbose_name="Chat Type",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the chat (for group chats)",
                        max_length=255,
                        null=True,
                        verbose_name="Chat Name",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the chat is active",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "last_message_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of the last message in this chat",
                        null=True,
                        verbose_name="Last Message At",
                    ),
                ),
                (
                    "cluster",
                    models.ForeignKey(
                        help_text="The cluster this object belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        related_query_name="%(class)s",
                        to="common.cluster",
                        verbose_name="cluster",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat",
                "verbose_name_plural": "Chats",
                "ordering": ["-last_message_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatParticipant",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creation date"
                    ),
                ),
                (
                    "created_by",
                    models.UUIDField(
                        help_text="the Id of the ClustR account user who added this object.",
                        null=True,
                        verbose_name="created by",
                    ),
                ),
                (
                    "last_modified_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="last modified date"
                    ),
                ),
                (
                    "last_modified_by",
                    models.UUIDField(
                        help_text="the Id of the ClustR account user who last modified this object.",
                        null=True,
                        verbose_name="last modified by",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="UUID primary key",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the user joined the chat",
                        verbose_name="Joined At",
                    ),
                ),
                (
                    "last_read_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the user last read messages in this chat",
                        null=True,
                        verbose_name="Last Read At",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the user is actively participating in the chat",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "chat",
                    models.ForeignKey(
                        help_text="The chat this participant belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="common.chat",
                        verbose_name="Chat",
                    ),
                ),
                (
                    "cluster",
                    models.ForeignKey(
                        help_text="The cluster this object belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        related_query_name="%(class)s",
                        to="common.cluster",
                        verbose_name="cluster",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user participating in the chat",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_participations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat Participant",
                "verbose_name_plural": "Chat Participants",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creation date"
                    ),
                ),
                (
                    "created_by",
                    models.UUIDField(
                        help_text="the Id of the ClustR account user who added this object.",
                        null=True,
                        verbose_name="created by",
                    ),
                ),
                (
                    "last_modified_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="last modified date"
                    ),
                ),
                (
                    "last_modified_by",
                    models.UUIDField(
                        help_text="the Id of the ClustR account user who last modified this object.",
                        null=True,
                        verbose_name="last modified by",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="UUID primary key",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("TEXT", "Text"),
                            ("IMAGE", "Image"),
                            ("FILE", "File"),
                            ("SYSTEM", "System"),
                        ],
                        default="TEXT",
                        help_text="Type of message content",
                        max_length=20,
                        verbose_name="Message Type",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="The message content", verbose_name="Content"
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        help_text="File attachment for the message",
                        null=True,
                        upload_to="chat_attachments/%Y/%m/%d/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "gif",
                                    "pdf",
                                    "doc",
                                    "docx",
                                    "txt",
                                ]
                            )
                        ],
                        verbose_name="Attachment",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SENT", "Sent"),
                            ("DELIVERED", "Delivered"),
                            ("READ", "Read"),
                            ("FAILED", "Failed"),
                        ],
                        default="SENT",
                        help_text="Delivery status of the message",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "is_edited",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the message has been edited",
                        verbose_name="Is Edited",
                    ),
                ),
                (
                    "edited_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the message was last edited",
                        null=True,
                        verbose_name="Edited At",
                    ),
                ),
                (
                    "chat",
                    models.ForeignKey(
                        help_text="The chat this message belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="common.chat",
                        verbose_name="Chat",
                    ),
                ),
                (
                    "cluster",
                    models.ForeignKey(
                        help_text="The cluster this object belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        related_query_name="%(class)s",
                        to="common.cluster",
                        verbose_name="cluster",
                    ),
                ),
                (
                    "reply_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="The message this is a reply to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replies",
                        to="common.message",
                        verbose_name="Reply To",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        help_text="The user who sent this message",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Sender",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="chat",
            index=models.Index(
                fields=["cluster", "chat_type"], name="common_chat_cluster_72fc84_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chat",
            index=models.Index(
                fields=["cluster", "is_active"], name="common_chat_cluster_be88c5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chat",
            index=models.Index(
                fields=["cluster", "last_message_at"],
                name="common_chat_cluster_bf270f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="chatparticipant",
            index=models.Index(
                fields=["cluster", "user"], name="common_chat_cluster_e0d20b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatparticipant",
            index=models.Index(
                fields=["cluster", "chat"], name="common_chat_cluster_bfe619_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatparticipant",
            index=models.Index(
                fields=["cluster", "is_active"], name="common_chat_cluster_14e590_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="chatparticipant",
            unique_together={("chat", "user")},
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["cluster", "chat", "created_at"],
                name="common_mess_cluster_5b3e75_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["cluster", "sender"], name="common_mess_cluster_2efd70_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["cluster", "message_type"],
                name="common_mess_cluster_1e0798_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["cluster", "status"], name="common_mess_cluster_ab5286_idx"
            ),
        ),
    ]
