# Generated by Django 4.2.9 on 2024-08-22 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0003_alter_cluster_admin"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cluster",
            name="admin",
        ),
        migrations.AddField(
            model_name="cluster",
            name="owner_id",
            field=models.UUIDField(
                default=None,
                editable=False,
                help_text="the Id of the BigCommand account owner.",
                verbose_name="owner id",
            ),
            preserve_default=False,
        ),
    ]
