# Generated by Django 5.2.4 on 2025-08-12 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0003_alter_announcement_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="idempotency_key",
            field=models.CharField(
                blank=True,
                help_text="Unique key to prevent duplicate transactions",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="idempotency key",
            ),
        ),
    ]
