# Generated by Django 5.2.4 on 2025-08-12 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0004_transaction_idempotency_key_chat_chatparticipant_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="chat",
        ),
        migrations.RemoveField(
            model_name="chatparticipant",
            name="chat",
        ),
        migrations.AlterUniqueTogether(
            name="chatparticipant",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="chatparticipant",
            name="cluster",
        ),
        migrations.RemoveField(
            model_name="chatparticipant",
            name="user",
        ),
        migrations.RemoveField(
            model_name="message",
            name="cluster",
        ),
        migrations.RemoveField(
            model_name="message",
            name="reply_to",
        ),
        migrations.RemoveField(
            model_name="message",
            name="sender",
        ),
        migrations.DeleteModel(
            name="Chat",
        ),
        migrations.DeleteModel(
            name="ChatParticipant",
        ),
        migrations.DeleteModel(
            name="Message",
        ),
    ]
