# Generated by Django 5.2.5 on 2025-11-15 05:49

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0004_transaction_idempotency_key"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creation date"
                    ),
                ),
                (
                    "created_by",
                    models.UUIDField(
                        help_text="the Id of the ClustR account user who added this object.",
                        null=True,
                        verbose_name="created by",
                    ),
                ),
                (
                    "last_modified_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="last modified date"
                    ),
                ),
                (
                    "last_modified_by",
                    models.UUIDField(
                        help_text="the Id of the ClustR account user who last modified this object.",
                        null=True,
                        verbose_name="last modified by",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="UUID primary key",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Display name for the chat (optional for direct messages)",
                        max_length=255,
                        null=True,
                        verbose_name="Chat Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Chat description or purpose",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "chat_type",
                    models.CharField(
                        choices=[
                            ("direct", "Direct Message"),
                            ("group", "Group Chat"),
                            ("announcement", "Announcement Chat"),
                            ("support", "Support Chat"),
                        ],
                        default="direct",
                        help_text="Type of chat conversation",
                        max_length=20,
                        verbose_name="Chat Type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("archived", "Archived"),
                            ("disabled", "Disabled"),
                        ],
                        default="active",
                        help_text="Current status of the chat",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this chat is public or private",
                        verbose_name="Is Public",
                    ),
                ),
                (
                    "is_moderated",
                    models.BooleanField(
                        default=False,
                        help_text="Whether messages in this chat require moderation",
                        verbose_name="Is Moderated",
                    ),
                ),
                (
                    "max_participants",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="Maximum number of participants allowed in this chat",
                        verbose_name="Maximum Participants",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        help_text="Avatar image for the chat",
                        null=True,
                        upload_to="chat_avatars/",
                        verbose_name="Chat Avatar",
                    ),
                ),
                (
                    "last_message_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of the last message in this chat",
                        null=True,
                        verbose_name="Last Message At",
                    ),
                ),
                (
                    "message_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total number of messages in this chat",
                        verbose_name="Message Count",
                    ),
                ),
                (
                    "cluster",
                    models.ForeignKey(
                        help_text="The cluster this object belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        related_query_name="%(class)s",
                        to="common.cluster",
                        verbose_name="cluster",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat",
                "verbose_name_plural": "Chats",
                "ordering": ["-last_message_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creation date"
                    ),
                ),
                (
                    "created_by",
                    models.UUIDField(
                        help_text="the Id of the ClustR account user who added this object.",
                        null=True,
                        verbose_name="created by",
                    ),
                ),
                (
                    "last_modified_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="last modified date"
                    ),
                ),
                (
                    "last_modified_by",
                    models.UUIDField(
                        help_text="the Id of the ClustR account user who last modified this object.",
                        null=True,
                        verbose_name="last modified by",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="UUID primary key",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="The title of the meeting",
                        max_length=255,
                        verbose_name="Meeting Title",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of the meeting",
                        verbose_name="Description",
                    ),
                ),
                (
                    "meeting_type",
                    models.CharField(
                        choices=[
                            ("community", "Community Meeting"),
                            ("committee", "Committee Meeting"),
                            ("emergency", "Emergency Meeting"),
                            ("board", "Board Meeting"),
                            ("general", "General Meeting"),
                            ("training", "Training Session"),
                            ("social", "Social Event"),
                        ],
                        default="general",
                        help_text="Type of meeting",
                        max_length=20,
                        verbose_name="Meeting Type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("live", "Live"),
                            ("ended", "Ended"),
                            ("cancelled", "Cancelled"),
                            ("postponed", "Postponed"),
                        ],
                        default="scheduled",
                        help_text="Current status of the meeting",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "scheduled_start",
                    models.DateTimeField(
                        help_text="When the meeting is scheduled to start",
                        verbose_name="Scheduled Start Time",
                    ),
                ),
                (
                    "scheduled_end",
                    models.DateTimeField(
                        help_text="When the meeting is scheduled to end",
                        verbose_name="Scheduled End Time",
                    ),
                ),
                (
                    "actual_start",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the meeting actually started",
                        null=True,
                        verbose_name="Actual Start Time",
                    ),
                ),
                (
                    "actual_end",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the meeting actually ended",
                        null=True,
                        verbose_name="Actual End Time",
                    ),
                ),
                (
                    "meeting_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to join the meeting (external platform)",
                        null=True,
                        verbose_name="Meeting URL",
                    ),
                ),
                (
                    "meeting_id",
                    models.CharField(
                        blank=True,
                        help_text="External meeting platform ID",
                        max_length=100,
                        null=True,
                        verbose_name="Meeting ID",
                    ),
                ),
                (
                    "passcode",
                    models.CharField(
                        blank=True,
                        help_text="Passcode required to join the meeting",
                        max_length=50,
                        null=True,
                        verbose_name="Meeting Passcode",
                    ),
                ),
                (
                    "max_participants",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="Maximum number of participants allowed",
                        verbose_name="Maximum Participants",
                    ),
                ),
                (
                    "is_recording_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Whether recording is enabled for this meeting",
                        verbose_name="Recording Enabled",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this meeting is open to all cluster members",
                        verbose_name="Is Public",
                    ),
                ),
                (
                    "requires_approval",
                    models.BooleanField(
                        default=False,
                        help_text="Whether participants need approval to join",
                        verbose_name="Requires Approval",
                    ),
                ),
                (
                    "agenda",
                    models.TextField(
                        blank=True,
                        help_text="Meeting agenda and topics to be discussed",
                        verbose_name="Agenda",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes taken during the meeting",
                        verbose_name="Meeting Notes",
                    ),
                ),
                (
                    "attachments",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of file attachments for the meeting",
                        verbose_name="Attachments",
                    ),
                ),
                (
                    "reminder_settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Settings for meeting reminders",
                        verbose_name="Reminder Settings",
                    ),
                ),
                (
                    "platform_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional data from external meeting platforms",
                        verbose_name="Platform Data",
                    ),
                ),
                (
                    "cluster",
                    models.ForeignKey(
                        help_text="The cluster this object belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        related_query_name="%(class)s",
                        to="common.cluster",
                        verbose_name="cluster",
                    ),
                ),
                (
                    "organizer",
                    models.ForeignKey(
                        help_text="The user who organized this meeting",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organized_meetings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Organizer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Meeting",
                "verbose_name_plural": "Meetings",
                "ordering": ["-scheduled_start"],
            },
        ),
        migrations.CreateModel(
            name="MeetingParticipant",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creation date"
                    ),
                ),
                (
                    "created_by",
                    models.UUIDField(
                        help_text="the Id of the ClustR account user who added this object.",
                        null=True,
                        verbose_name="created by",
                    ),
                ),
                (
                    "last_modified_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="last modified date"
                    ),
                ),
                (
                    "last_modified_by",
                    models.UUIDField(
                        help_text="the Id of the ClustR account user who last modified this object.",
                        null=True,
                        verbose_name="last modified by",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="UUID primary key",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("host", "Host"),
                            ("co_host", "Co-Host"),
                            ("moderator", "Moderator"),
                            ("participant", "Participant"),
                            ("observer", "Observer"),
                        ],
                        default="participant",
                        help_text="The role of the participant in this meeting",
                        max_length=20,
                        verbose_name="Role",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("invited", "Invited"),
                            ("confirmed", "Confirmed"),
                            ("declined", "Declined"),
                            ("joined", "Joined"),
                            ("left", "Left"),
                            ("removed", "Removed"),
                        ],
                        default="invited",
                        help_text="Current status of the participant",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "invited_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the participant was invited to the meeting",
                        verbose_name="Invited At",
                    ),
                ),
                (
                    "responded_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the participant responded to the invitation",
                        null=True,
                        verbose_name="Responded At",
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the participant joined the meeting",
                        null=True,
                        verbose_name="Joined At",
                    ),
                ),
                (
                    "left_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the participant left the meeting",
                        null=True,
                        verbose_name="Left At",
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total time spent in the meeting in minutes",
                        verbose_name="Duration (Minutes)",
                    ),
                ),
                (
                    "can_share_screen",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the participant can share their screen",
                        verbose_name="Can Share Screen",
                    ),
                ),
                (
                    "can_use_microphone",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the participant can use their microphone",
                        verbose_name="Can Use Microphone",
                    ),
                ),
                (
                    "can_use_camera",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the participant can use their camera",
                        verbose_name="Can Use Camera",
                    ),
                ),
                (
                    "can_use_chat",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the participant can use the meeting chat",
                        verbose_name="Can Use Chat",
                    ),
                ),
                (
                    "is_muted",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the participant's microphone is muted",
                        verbose_name="Is Muted",
                    ),
                ),
                (
                    "camera_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the participant's camera is enabled",
                        verbose_name="Camera Enabled",
                    ),
                ),
                (
                    "connection_quality",
                    models.CharField(
                        choices=[
                            ("excellent", "Excellent"),
                            ("good", "Good"),
                            ("fair", "Fair"),
                            ("poor", "Poor"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        help_text="Quality of the participant's connection",
                        max_length=20,
                        verbose_name="Connection Quality",
                    ),
                ),
                (
                    "device_info",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Information about the participant's device",
                        verbose_name="Device Info",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about the participant",
                        verbose_name="Notes",
                    ),
                ),
                (
                    "cluster",
                    models.ForeignKey(
                        help_text="The cluster this object belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        related_query_name="%(class)s",
                        to="common.cluster",
                        verbose_name="cluster",
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        help_text="The meeting this participant belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="common.meeting",
                        verbose_name="Meeting",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user participating in the meeting",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meeting_participations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Meeting Participant",
                "verbose_name_plural": "Meeting Participants",
                "ordering": ["-invited_at"],
            },
        ),
        migrations.CreateModel(
            name="MeetingRecording",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creation date"
                    ),
                ),
                (
                    "created_by",
                    models.UUIDField(
                        help_text="the Id of the ClustR account user who added this object.",
                        null=True,
                        verbose_name="created by",
                    ),
                ),
                (
                    "last_modified_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="last modified date"
                    ),
                ),
                (
                    "last_modified_by",
                    models.UUIDField(
                        help_text="the Id of the ClustR account user who last modified this object.",
                        null=True,
                        verbose_name="last modified by",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="UUID primary key",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the recording",
                        max_length=255,
                        verbose_name="Recording Title",
                    ),
                ),
                (
                    "recording_type",
                    models.CharField(
                        choices=[
                            ("full", "Full Meeting Recording"),
                            ("audio_only", "Audio Only"),
                            ("screen_share", "Screen Share Only"),
                            ("highlights", "Meeting Highlights"),
                        ],
                        default="full",
                        help_text="Type of recording",
                        max_length=20,
                        verbose_name="Recording Type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("recording", "Recording"),
                            ("processing", "Processing"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                            ("archived", "Archived"),
                            ("deleted", "Deleted"),
                        ],
                        default="recording",
                        help_text="Current status of the recording",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="The recording file",
                        null=True,
                        upload_to="meeting_recordings/%Y/%m/%d/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "mp4",
                                    "avi",
                                    "mov",
                                    "wmv",
                                    "flv",
                                    "webm",
                                    "mp3",
                                    "wav",
                                    "ogg",
                                ]
                            )
                        ],
                        verbose_name="Recording File",
                    ),
                ),
                (
                    "file_size",
                    models.PositiveBigIntegerField(
                        default=0,
                        help_text="Size of the recording file in bytes",
                        verbose_name="File Size",
                    ),
                ),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Duration of the recording in seconds",
                        verbose_name="Duration (Seconds)",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        help_text="When the recording started",
                        verbose_name="Recording Start Time",
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the recording ended",
                        null=True,
                        verbose_name="Recording End Time",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        help_text="Thumbnail image for the recording",
                        null=True,
                        upload_to="meeting_thumbnails/%Y/%m/%d/",
                        verbose_name="Thumbnail",
                    ),
                ),
                (
                    "transcript",
                    models.TextField(
                        blank=True,
                        help_text="Auto-generated transcript of the recording",
                        null=True,
                        verbose_name="Transcript",
                    ),
                ),
                (
                    "external_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to external recording service",
                        null=True,
                        verbose_name="External URL",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        help_text="ID from external recording service",
                        max_length=255,
                        null=True,
                        verbose_name="External ID",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this recording is publicly accessible",
                        verbose_name="Is Public",
                    ),
                ),
                (
                    "requires_authentication",
                    models.BooleanField(
                        default=True,
                        help_text="Whether viewing requires authentication",
                        verbose_name="Requires Authentication",
                    ),
                ),
                (
                    "download_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the recording can be downloaded",
                        verbose_name="Download Enabled",
                    ),
                ),
                (
                    "auto_delete_after_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Number of days after which to auto-delete the recording",
                        null=True,
                        verbose_name="Auto Delete After Days",
                    ),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of times the recording has been viewed",
                        verbose_name="View Count",
                    ),
                ),
                (
                    "download_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of times the recording has been downloaded",
                        verbose_name="Download Count",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata about the recording",
                        verbose_name="Metadata",
                    ),
                ),
                (
                    "processing_error",
                    models.TextField(
                        blank=True,
                        help_text="Error message if processing failed",
                        null=True,
                        verbose_name="Processing Error",
                    ),
                ),
                (
                    "cluster",
                    models.ForeignKey(
                        help_text="The cluster this object belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        related_query_name="%(class)s",
                        to="common.cluster",
                        verbose_name="cluster",
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        help_text="The meeting this recording belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recordings",
                        to="common.meeting",
                        verbose_name="Meeting",
                    ),
                ),
            ],
            options={
                "verbose_name": "Meeting Recording",
                "verbose_name_plural": "Meeting Recordings",
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creation date"
                    ),
                ),
                (
                    "created_by",
                    models.UUIDField(
                        help_text="the Id of the ClustR account user who added this object.",
                        null=True,
                        verbose_name="created by",
                    ),
                ),
                (
                    "last_modified_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="last modified date"
                    ),
                ),
                (
                    "last_modified_by",
                    models.UUIDField(
                        help_text="the Id of the ClustR account user who last modified this object.",
                        null=True,
                        verbose_name="last modified by",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="UUID primary key",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        help_text="The message content",
                        verbose_name="Content",
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "Text Message"),
                            ("image", "Image"),
                            ("file", "File"),
                            ("audio", "Audio"),
                            ("video", "Video"),
                            ("location", "Location"),
                            ("system", "System Message"),
                            ("announcement", "Announcement"),
                        ],
                        default="text",
                        help_text="Type of message content",
                        max_length=20,
                        verbose_name="Message Type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("read", "Read"),
                            ("failed", "Failed"),
                            ("pending", "Pending"),
                            ("moderated", "Under Moderation"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="sent",
                        help_text="Current status of the message",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "is_edited",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this message has been edited",
                        verbose_name="Is Edited",
                    ),
                ),
                (
                    "edited_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the message was last edited",
                        null=True,
                        verbose_name="Edited At",
                    ),
                ),
                (
                    "is_pinned",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this message is pinned in the chat",
                        verbose_name="Is Pinned",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this message has been deleted",
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the message was deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata for the message (location, file info, etc.)",
                        verbose_name="Metadata",
                    ),
                ),
                (
                    "moderation_reason",
                    models.TextField(
                        blank=True,
                        help_text="Reason for moderation action",
                        null=True,
                        verbose_name="Moderation Reason",
                    ),
                ),
                (
                    "chat",
                    models.ForeignKey(
                        help_text="The chat this message belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="common.chat",
                        verbose_name="Chat",
                    ),
                ),
                (
                    "cluster",
                    models.ForeignKey(
                        help_text="The cluster this object belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        related_query_name="%(class)s",
                        to="common.cluster",
                        verbose_name="cluster",
                    ),
                ),
                (
                    "reply_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="The message this is a reply to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replies",
                        to="common.message",
                        verbose_name="Reply To",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who sent this message",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Sender",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatParticipant",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creation date"
                    ),
                ),
                (
                    "created_by",
                    models.UUIDField(
                        help_text="the Id of the ClustR account user who added this object.",
                        null=True,
                        verbose_name="created by",
                    ),
                ),
                (
                    "last_modified_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="last modified date"
                    ),
                ),
                (
                    "last_modified_by",
                    models.UUIDField(
                        help_text="the Id of the ClustR account user who last modified this object.",
                        null=True,
                        verbose_name="last modified by",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="UUID primary key",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the user is currently active in this chat",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "is_admin",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the user has admin privileges in this chat",
                        verbose_name="Is Admin",
                    ),
                ),
                (
                    "is_moderator",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the user can moderate messages in this chat",
                        verbose_name="Is Moderator",
                    ),
                ),
                (
                    "can_send_messages",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the user can send messages in this chat",
                        verbose_name="Can Send Messages",
                    ),
                ),
                (
                    "can_add_participants",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the user can add new participants to this chat",
                        verbose_name="Can Add Participants",
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the user joined this chat",
                        verbose_name="Joined At",
                    ),
                ),
                (
                    "left_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the user left this chat",
                        null=True,
                        verbose_name="Left At",
                    ),
                ),
                (
                    "last_read_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the user last read messages in this chat",
                        null=True,
                        verbose_name="Last Read At",
                    ),
                ),
                (
                    "notification_settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="User's notification preferences for this chat",
                        verbose_name="Notification Settings",
                    ),
                ),
                (
                    "muted_until",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the chat notifications will be unmuted for this user",
                        null=True,
                        verbose_name="Muted Until",
                    ),
                ),
                (
                    "chat",
                    models.ForeignKey(
                        help_text="The chat this participant belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="common.chat",
                        verbose_name="Chat",
                    ),
                ),
                (
                    "cluster",
                    models.ForeignKey(
                        help_text="The cluster this object belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        related_query_name="%(class)s",
                        to="common.cluster",
                        verbose_name="cluster",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user participating in the chat",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_participations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
                (
                    "last_message_read",
                    models.ForeignKey(
                        blank=True,
                        help_text="The last message read by this participant",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="read_by_participants",
                        to="common.message",
                        verbose_name="Last Message Read",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat Participant",
                "verbose_name_plural": "Chat Participants",
                "ordering": ["-joined_at"],
            },
        ),
        migrations.CreateModel(
            name="MessageAttachment",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creation date"
                    ),
                ),
                (
                    "created_by",
                    models.UUIDField(
                        help_text="the Id of the ClustR account user who added this object.",
                        null=True,
                        verbose_name="created by",
                    ),
                ),
                (
                    "last_modified_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="last modified date"
                    ),
                ),
                (
                    "last_modified_by",
                    models.UUIDField(
                        help_text="the Id of the ClustR account user who last modified this object.",
                        null=True,
                        verbose_name="last modified by",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="UUID primary key",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="The attached file",
                        upload_to="chat_attachments/%Y/%m/%d/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "pdf",
                                    "doc",
                                    "docx",
                                    "txt",
                                    "rtf",
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "gif",
                                    "bmp",
                                    "webp",
                                    "mp4",
                                    "avi",
                                    "mov",
                                    "wmv",
                                    "flv",
                                    "webm",
                                    "mp3",
                                    "wav",
                                    "ogg",
                                    "aac",
                                    "m4a",
                                    "zip",
                                    "rar",
                                    "7z",
                                    "tar",
                                    "gz",
                                    "xls",
                                    "xlsx",
                                    "csv",
                                    "ppt",
                                    "pptx",
                                ]
                            )
                        ],
                        verbose_name="File",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(
                        help_text="The original name of the uploaded file",
                        max_length=255,
                        verbose_name="Original Filename",
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        help_text="Size of the file in bytes", verbose_name="File Size"
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(
                        help_text="MIME type of the file",
                        max_length=100,
                        verbose_name="MIME Type",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        help_text="Thumbnail image for the attachment",
                        null=True,
                        upload_to="chat_thumbnails/%Y/%m/%d/",
                        verbose_name="Thumbnail",
                    ),
                ),
                (
                    "cluster",
                    models.ForeignKey(
                        help_text="The cluster this object belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        related_query_name="%(class)s",
                        to="common.cluster",
                        verbose_name="cluster",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        help_text="The message this attachment belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="common.message",
                        verbose_name="Message",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message Attachment",
                "verbose_name_plural": "Message Attachments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="chat",
            index=models.Index(
                fields=["cluster", "chat_type"], name="common_chat_cluster_72fc84_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chat",
            index=models.Index(
                fields=["cluster", "status"], name="common_chat_cluster_df3364_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chat",
            index=models.Index(
                fields=["last_message_at"], name="common_chat_last_me_762f78_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meeting",
            index=models.Index(
                fields=["cluster", "scheduled_start"],
                name="common_meet_cluster_b2bb87_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="meeting",
            index=models.Index(
                fields=["organizer", "scheduled_start"],
                name="common_meet_organiz_ede479_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="meeting",
            index=models.Index(
                fields=["status", "scheduled_start"],
                name="common_meet_status_5a8ebe_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="meeting",
            index=models.Index(
                fields=["meeting_type"], name="common_meet_meeting_381751_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meetingparticipant",
            index=models.Index(
                fields=["meeting", "status"], name="common_meet_meeting_fba2af_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meetingparticipant",
            index=models.Index(
                fields=["user", "status"], name="common_meet_user_id_20e43c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meetingparticipant",
            index=models.Index(fields=["role"], name="common_meet_role_6cbc5a_idx"),
        ),
        migrations.AddIndex(
            model_name="meetingparticipant",
            index=models.Index(
                fields=["joined_at"], name="common_meet_joined__48629e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="meetingparticipant",
            unique_together={("meeting", "user")},
        ),
        migrations.AddIndex(
            model_name="meetingrecording",
            index=models.Index(
                fields=["meeting", "status"], name="common_meet_meeting_e1f90c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meetingrecording",
            index=models.Index(
                fields=["status", "start_time"], name="common_meet_status_387f5c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meetingrecording",
            index=models.Index(
                fields=["recording_type"], name="common_meet_recordi_12a94d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meetingrecording",
            index=models.Index(
                fields=["is_public"], name="common_meet_is_publ_20af75_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["chat", "created_at"], name="common_mess_chat_id_ee576b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["sender", "created_at"], name="common_mess_sender__eba9af_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["message_type"], name="common_mess_message_306413_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["status"], name="common_mess_status_f1dbc5_idx"),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["is_deleted", "created_at"],
                name="common_mess_is_dele_8bda60_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="chatparticipant",
            index=models.Index(
                fields=["chat", "is_active"], name="common_chat_chat_id_64d420_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatparticipant",
            index=models.Index(
                fields=["user", "is_active"], name="common_chat_user_id_ef5f73_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatparticipant",
            index=models.Index(
                fields=["last_read_at"], name="common_chat_last_re_11e5c7_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="chatparticipant",
            unique_together={("chat", "user")},
        ),
    ]
