# Generated by Django 5.2.5 on 2025-11-30 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0005_chat_meeting_meetingparticipant_meetingrecording_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="bill",
            field=models.ForeignKey(
                blank=True,
                help_text="The bill this transaction is paying for (for cluster-managed bills)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="common.bill",
                verbose_name="bill",
            ),
        ),
    ]
