# Generated by Django 5.2.5 on 2026-01-03 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0006_transaction_bill"),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenancelog",
            name="related_ticket",
            field=models.ForeignKey(
                blank=True,
                help_text="The issue ticket that initiated this maintenance work",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="maintenance_logs",
                to="common.issueticket",
                verbose_name="related ticket",
            ),
        ),
    ]
