# Generated by Django 5.2.5 on 2026-01-07 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0007_maintenancelog_related_ticket"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="emergencycontact",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="User who owns this contact (null for estate-wide contacts)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="common_emergency_contacts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
    ]
