# Generated by Django 5.2.5 on 2026-01-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0008_alter_emergencycontact_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="priority",
            field=models.CharField(
                choices=[
                    ("LOW", "Low"),
                    ("MEDIUM", "Medium"),
                    ("HIGH", "High"),
                    ("URGENT", "Urgent"),
                ],
                default="MEDIUM",
                help_text="Priority level of the announcement",
                max_length=10,
                verbose_name="priority",
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("PUBLISHED", "Published"),
                    ("ARCHIVED", "Archived"),
                ],
                default="DRAFT",
                help_text="Current status of the announcement",
                max_length=10,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="category",
            field=models.CharField(
                choices=[
                    ("GENERAL", "General"),
                    ("MAINTENANCE", "Maintenance"),
                    ("SECURITY", "Security"),
                    ("EVENT", "Event"),
                    ("EMERGENCY", "Emergency"),
                    ("BILLING", "Billing"),
                    ("OTHER", "Other"),
                ],
                default="GENERAL",
                help_text="Category of the announcement",
                max_length=20,
                verbose_name="category",
            ),
        ),
    ]
