# Generated by Django 5.2.5 on 2026-01-25 18:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0009_announcement_priority_announcement_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creation date"
                    ),
                ),
                (
                    "created_by",
                    models.UUIDField(
                        help_text="the Id of the ClustR account user who added this object.",
                        null=True,
                        verbose_name="created by",
                    ),
                ),
                (
                    "last_modified_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="last modified date"
                    ),
                ),
                (
                    "last_modified_by",
                    models.UUIDField(
                        help_text="the Id of the ClustR account user who last modified this object.",
                        null=True,
                        verbose_name="last modified by",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="UUID primary key",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Full name of the staff member",
                        max_length=200,
                        verbose_name="name",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Email address for notifications (optional)",
                        max_length=254,
                        null=True,
                        verbose_name="email",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        help_text="Contact phone number",
                        max_length=20,
                        verbose_name="phone number",
                    ),
                ),
                (
                    "staff_type",
                    models.CharField(
                        choices=[
                            ("SECURITY", "Security"),
                            ("MAINTENANCE", "Maintenance"),
                            ("CLEANING", "Cleaning"),
                            ("RECEPTION", "Reception"),
                            ("GARDENING", "Gardening"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        help_text="Primary type of work this staff member performs",
                        max_length=20,
                        verbose_name="staff type",
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(
                        blank=True,
                        help_text="Unique employee identifier",
                        max_length=50,
                        verbose_name="employee ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the staff member is currently active",
                        verbose_name="is active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateField(
                        auto_now_add=True,
                        help_text="Date when the staff member joined",
                        verbose_name="date joined",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about the staff member",
                        verbose_name="notes",
                    ),
                ),
                (
                    "cluster",
                    models.ForeignKey(
                        help_text="The cluster this object belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        related_query_name="%(class)s",
                        to="common.cluster",
                        verbose_name="cluster",
                    ),
                ),
            ],
            options={
                "verbose_name": "staff member",
                "verbose_name_plural": "staff members",
                "ordering": ["name"],
                "default_permissions": [],
            },
        ),
        migrations.AlterField(
            model_name="shift",
            name="assigned_staff",
            field=models.ForeignKey(
                help_text="Staff member assigned to this shift",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_shifts",
                to="common.staff",
                verbose_name="assigned staff",
            ),
        ),
        migrations.AlterField(
            model_name="shiftswaprequest",
            name="requested_by",
            field=models.ForeignKey(
                help_text="Staff member requesting the swap",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shift_swap_requests",
                to="common.staff",
                verbose_name="requested by",
            ),
        ),
        migrations.AlterField(
            model_name="shiftswaprequest",
            name="requested_with",
            field=models.ForeignKey(
                help_text="Staff member to swap with",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shift_swap_offers",
                to="common.staff",
                verbose_name="requested with",
            ),
        ),
        migrations.AddIndex(
            model_name="staff",
            index=models.Index(
                fields=["staff_type"], name="common_staf_staff_t_f3fcec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staff",
            index=models.Index(
                fields=["is_active"], name="common_staf_is_acti_eddcb6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staff",
            index=models.Index(
                fields=["cluster", "is_active"], name="common_staf_cluster_44414d_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="staff",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("employee_id__isnull", False),
                    models.Q(("employee_id", ""), _negated=True),
                ),
                fields=("cluster", "employee_id"),
                name="unique_employee_id_per_cluster",
            ),
        ),
    ]
