# Generated by Django 5.2.4 on 2025-07-30 10:17

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExportTask",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creation date"
                    ),
                ),
                (
                    "last_modified_by",
                    models.UUIDField(
                        help_text="the Id of the ClustR account user who last modified this object.",
                        null=True,
                        verbose_name="last modified by",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="UUID primary key",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "owner_id",
                    models.UUIDField(
                        help_text="the Id of the ClustR account user who created this data exchange.",
                        verbose_name="created by",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="completion date"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IN_PROGRESS", "In Progress"),
                            ("SUCCESS", "Success"),
                            ("FAIL", "Fail"),
                        ],
                        max_length=50,
                        verbose_name="status",
                    ),
                ),
                (
                    "notify_on_success",
                    models.BooleanField(
                        default=False,
                        help_text="notify the user after an import or export succeeds",
                        verbose_name="notify on success",
                    ),
                ),
                (
                    "external_file_id",
                    models.UUIDField(
                        help_text="the external file id (AWS/Cloudinary) if the file is stored in external.",
                        null=True,
                        verbose_name="external file id",
                    ),
                ),
                (
                    "sql_query",
                    models.TextField(
                        help_text="the SQL query used to extract the exported data. Maybe from queryset.query",
                        verbose_name="sql query",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        help_text="django model content type to be exported or imported.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="content type",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="primary user",
                    ),
                ),
            ],
            options={
                "verbose_name": "export task",
                "verbose_name_plural": "export tasks",
                "ordering": ["-created_at"],
                "abstract": False,
                "default_permissions": [],
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="data_exchan_created_e768fb_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ImportTask",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creation date"
                    ),
                ),
                (
                    "last_modified_by",
                    models.UUIDField(
                        help_text="the Id of the ClustR account user who last modified this object.",
                        null=True,
                        verbose_name="last modified by",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="UUID primary key",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "owner_id",
                    models.UUIDField(
                        help_text="the Id of the ClustR account user who created this data exchange.",
                        verbose_name="created by",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="completion date"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IN_PROGRESS", "In Progress"),
                            ("SUCCESS", "Success"),
                            ("FAIL", "Fail"),
                        ],
                        max_length=50,
                        verbose_name="status",
                    ),
                ),
                (
                    "notify_on_success",
                    models.BooleanField(
                        default=False,
                        help_text="notify the user after an import or export succeeds",
                        verbose_name="notify on success",
                    ),
                ),
                (
                    "imported_object_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=40),
                        blank=True,
                        default=list,
                        help_text="The IDs of the imported objects",
                        size=None,
                        verbose_name="Import IDs",
                    ),
                ),
                (
                    "errors",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="A list of dictionary of serialized RowError objects encountered during the import",
                        verbose_name="errors",
                    ),
                ),
                (
                    "total_skipped",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="The total number of rows that were fully skipped due to errors",
                        verbose_name="total skipped",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        help_text="django model content type to be exported or imported.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="content type",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="primary user",
                    ),
                ),
            ],
            options={
                "verbose_name": "import task",
                "verbose_name_plural": "import tasks",
                "ordering": ["-created_at"],
                "abstract": False,
                "default_permissions": [],
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="data_exchan_created_9b3de8_idx"
                    )
                ],
            },
        ),
    ]
