# Generated by Django 4.2.9 on 2024-08-11 19:31

import accounts.models.email_verification
import accounts.models.users
import core.common.code_generator
from django.conf import settings
import django.contrib.auth.models
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountUser",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="UUID primary key",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_by",
                    models.UUIDField(
                        editable=False,
                        help_text="the Id of the ClustR account user who added this object.",
                        null=True,
                        verbose_name="created by",
                    ),
                ),
                (
                    "last_modified_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="last modified date"
                    ),
                ),
                (
                    "last_modified_by",
                    models.UUIDField(
                        editable=False,
                        help_text="the Id of the ClustR account user who last modified this object.",
                        null=True,
                        verbose_name="last modified by",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="name of user"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=16, verbose_name="phone number"
                    ),
                ),
                (
                    "email_address",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email address"
                    ),
                ),
                (
                    "unit_address",
                    models.TextField(
                        help_text="This is the address of the resident in the cluster",
                        null=True,
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        default=accounts.models.users.generate_external_id,
                        help_text="This is the external resident id used for verification and display purposes",
                    ),
                ),
                (
                    "profile_image_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Profile image of the user.",
                        verbose_name="profile image url",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Has this user completed email verification flow?",
                        verbose_name="Is verified?",
                    ),
                ),
                (
                    "approved_by_admin",
                    models.BooleanField(
                        default=False,
                        help_text="Has this account been approved by an admin for the specified cluster?",
                        verbose_name="Approved by admin?",
                    ),
                ),
                ("is_cluster_admin", models.BooleanField(default=False)),
                ("is_owner", models.BooleanField(default=False)),
                ("is_cluster_staff", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "ordering": ("-date_joined",),
                "permissions": [
                    ("ManageInvitation", "manage invitation"),
                    ("ManageVisitRequest", "manage visit request"),
                    ("ManageGuest", "manage guest"),
                    ("ManageEvent", "manage event"),
                    ("ManageWard", "manage ward"),
                    ("ManageExit", "manage exit"),
                    ("ManageAccountUser", "manage account user"),
                    ("ManageResidents", "manage residents"),
                    ("ManageRoles", "manage roles"),
                    ("ManageUserPermissions", "manage user permissions"),
                    ("ManageEmergency", "manage emergency"),
                    ("ManageEmergencyContacts", "manage emergency contacts"),
                    ("ManageComplaint", "manage complaint"),
                    ("ManageAnnouncement", "manage announcement"),
                    ("ManagePoll", "manage poll"),
                    ("ChangePollSettings", "change poll settings"),
                    ("ManageOptions", "manage options"),
                    ("ManageResponses", "manage responses"),
                    ("ManageDocuments", "manage documents"),
                    ("ManageWorkShift", "manage work shift"),
                    ("ManageWorkTask", "manage work task"),
                    ("ManageSeller", "manage seller"),
                    ("ManagePost", "manage post"),
                    ("ManageTags", "manage tags"),
                    ("ManageReview", "manage review"),
                    ("ManageNotification", "manage notification"),
                    ("ReceiveNotifications", "receive notifications"),
                    ("ManageWallet", "manage wallet"),
                    ("ManageBill", "manage bill"),
                    ("PayBills", "pay bills"),
                    ("ManageTransaction", "manage transaction"),
                    ("ManageHandyMen", "manage handy men"),
                    ("ManageDomesticStaff", "manage domestic staff"),
                ],
                "default_permissions": [],
            },
            managers=[
                ("objects", accounts.models.users.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "group_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="auth.group",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creation date"
                    ),
                ),
                (
                    "created_by",
                    models.UUIDField(
                        editable=False,
                        help_text="the Id of the ClustR account user who added this object.",
                        null=True,
                        verbose_name="created by",
                    ),
                ),
                (
                    "last_modified_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="last modified date"
                    ),
                ),
                (
                    "last_modified_by",
                    models.UUIDField(
                        editable=False,
                        help_text="the Id of the ClustR account user who last modified this object.",
                        null=True,
                        verbose_name="last modified by",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Description of the role.",
                        verbose_name="description",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        editable=False,
                        help_text="The admin this role belongs to",
                        limit_choices_to={
                            "is_cluster_admin": True,
                            "is_owner": True,
                            "is_staff": False,
                        },
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        related_query_name="role",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Primary account",
                    ),
                ),
            ],
            options={
                "verbose_name": "role",
                "verbose_name_plural": "roles",
                "ordering": ["-created_at"],
                "default_permissions": [],
            },
            bases=("auth.group", models.Model),
            managers=[
                ("objects", django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name="PreviousPasswords",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="UUID primary key",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "passwords",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            max_length=128, verbose_name="password"
                        ),
                        default=list,
                        help_text="List of password hash of users old passwords",
                        null=True,
                        size=200,
                    ),
                ),
                (
                    "last_modified_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="last modified date"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="previous_passwords",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "previous passwords",
                "verbose_name_plural": "previous passwords",
                "default_permissions": [],
            },
        ),
        migrations.CreateModel(
            name="UserVerification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="UUID primary key",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                ("otp", models.CharField(max_length=5, null=True)),
                ("token", models.CharField(max_length=255, null=True)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("NEW_OWNER", "New Owner"),
                            (
                                "NEW_SUBUSER_ACCOUNT_TO_SUBUSER",
                                "New Subuser Account To Subuser",
                            ),
                            (
                                "NEW_SUBUSER_ACCOUNT_TO_PRIMARY",
                                "New Subuser Account To Primary",
                            ),
                            ("SUBUSER_ACCOUNT_UPDATE", "Subuser Account Update"),
                            (
                                "ONBOARDING_OTP_PASSWORD_RESET",
                                "Onboarding Otp Password Reset",
                            ),
                            (
                                "ONBOARDING_TOKEN_PASSWORD_RESET",
                                "Onboarding Token Password Reset",
                            ),
                            ("WEB_TOKEN_PASSWORD_RESET", "Web Token Password Reset"),
                            ("OTP_PASSWORD_RESET", "Otp Password Reset"),
                            ("RESEND_OTP", "Resend Otp"),
                            ("RESEND_WEB_TOKEN", "Resend Web Token"),
                            ("PASSWORD_CHANGED", "Password Changed"),
                            ("IMPORT_SUCCESS", "Import Success"),
                            ("EXPORT_SUCCESS", "Export Success"),
                        ],
                        max_length=50,
                        verbose_name="Notification type",
                    ),
                ),
                (
                    "requested_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Request date"
                    ),
                ),
                (
                    "is_used",
                    models.BooleanField(
                        default=False,
                        help_text="Has this token been used successfully?",
                        verbose_name="Is used?",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            bases=(
                models.Model,
                accounts.models.email_verification.BaseUserToken,
                core.common.code_generator.CodeGenerator,
            ),
        ),
    ]
