# Generated by Django 5.2.4 on 2025-07-30 10:17

import accounts.models.email_verification
import accounts.models.users
import core.common.code_generator
import django.contrib.auth.models
import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountUser",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "created_by",
                    models.UUIDField(
                        help_text="the Id of the ClustR account user who added this object.",
                        null=True,
                        verbose_name="created by",
                    ),
                ),
                (
                    "last_modified_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="last modified date"
                    ),
                ),
                (
                    "last_modified_by",
                    models.UUIDField(
                        help_text="the Id of the ClustR account user who last modified this object.",
                        null=True,
                        verbose_name="last modified by",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="UUID primary key",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name of user")),
                (
                    "phone_number",
                    models.CharField(
                        help_text="The phone number for this subscription in E.164 format. See details: https://www.twilio.com/docs/glossary/what-e164",
                        max_length=16,
                        validators=[
                            django.core.validators.MinLengthValidator(4),
                            django.core.validators.RegexValidator(
                                "^\\+[1-9]\\d{1,14}$"
                            ),
                        ],
                        verbose_name="phone number",
                    ),
                ),
                (
                    "email_address",
                    models.EmailField(
                        max_length=100, unique=True, verbose_name="email address"
                    ),
                ),
                (
                    "unit_address",
                    models.TextField(
                        help_text="This is the address of the resident in the cluster",
                        null=True,
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        default=accounts.models.users.generate_external_id,
                        help_text="This is the external resident id used for verification and display purposes",
                    ),
                ),
                (
                    "profile_image_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Profile image of the user.",
                        verbose_name="profile image url",
                    ),
                ),
                (
                    "property_owner",
                    models.BooleanField(default=False, verbose_name="Property owner"),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Has this user completed email verification flow?",
                        verbose_name="Is verified?",
                    ),
                ),
                (
                    "is_phone_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Has this user completed phone verification flow?",
                        verbose_name="Is phone verified?",
                    ),
                ),
                (
                    "approved_by_admin",
                    models.BooleanField(
                        default=False,
                        help_text="Has this account been approved by an admin for the specified cluster?",
                        verbose_name="Approved by admin?",
                    ),
                ),
                (
                    "failed_login_attempts",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of consecutive failed login attempts",
                        verbose_name="Failed login attempts",
                    ),
                ),
                (
                    "last_failed_login",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of the last failed login attempt",
                        null=True,
                        verbose_name="Last failed login",
                    ),
                ),
                (
                    "account_locked_until",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp until which the account is locked due to failed login attempts",
                        null=True,
                        verbose_name="Account locked until",
                    ),
                ),
                (
                    "last_login_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address of the last successful login",
                        null=True,
                        verbose_name="Last login IP",
                    ),
                ),
                ("is_cluster_admin", models.BooleanField(default=False)),
                ("is_owner", models.BooleanField(default=False)),
                ("is_cluster_staff", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "ordering": ("-date_joined",),
                "permissions": [
                    ("ViewInvitation", "view invitation"),
                    ("ManageInvitation", "manage invitation"),
                    ("ViewVisitRequest", "view visit request"),
                    ("ManageVisitRequest", "manage visit request"),
                    ("ViewGuest", "view guest"),
                    ("ManageGuest", "manage guest"),
                    ("ViewEvent", "view event"),
                    ("ManageEvent", "manage event"),
                    ("ViewWard", "view ward"),
                    ("ManageWard", "manage ward"),
                    ("ViewExit", "view exit"),
                    ("ManageExit", "manage exit"),
                    ("ViewAccountUser", "view account user"),
                    ("ManageAccountUser", "manage account user"),
                    ("ViewResidents", "view residents"),
                    ("ManageResidents", "manage residents"),
                    ("ViewRoles", "view roles"),
                    ("ManageRoles", "manage roles"),
                    ("ViewEmergency", "view emergency"),
                    ("ManageEmergency", "manage emergency"),
                    ("ViewEmergencyContacts", "view emergency contacts"),
                    ("ManageEmergencyContacts", "manage emergency contacts"),
                    ("ViewComplaint", "view complaint"),
                    ("ManageComplaint", "manage complaint"),
                    ("ViewAnnouncement", "view announcement"),
                    ("ManageAnnouncement", "manage announcement"),
                    ("ViewPoll", "view poll"),
                    ("ManagePoll", "manage poll"),
                    ("ChangePollSettings", "change poll settings"),
                    ("ViewOptions", "view options"),
                    ("ManageOptions", "manage options"),
                    ("ViewResponses", "view responses"),
                    ("ManageResponses", "manage responses"),
                    ("ViewDocuments", "view documents"),
                    ("ManageDocuments", "manage documents"),
                    ("ViewWorkShift", "view work shift"),
                    ("ManageWorkShift", "manage work shift"),
                    ("ViewWorkTask", "view work task"),
                    ("ManageWorkTask", "manage work task"),
                    ("ViewSeller", "view seller"),
                    ("ManageSeller", "manage seller"),
                    ("ViewPost", "view post"),
                    ("ManagePost", "manage post"),
                    ("ViewTags", "view tags"),
                    ("ManageTags", "manage tags"),
                    ("ViewReview", "view review"),
                    ("ManageReview", "manage review"),
                    ("ViewNotification", "view notification"),
                    ("ManageNotification", "manage notification"),
                    ("ReceiveNotifications", "receive notifications"),
                    ("ViewWallet", "view wallet"),
                    ("ManageWallet", "manage wallet"),
                    ("ViewBill", "view bill"),
                    ("ManageBill", "manage bill"),
                    ("PayBills", "pay bills"),
                    ("ViewTransaction", "view transaction"),
                    ("ManageTransaction", "manage transaction"),
                    ("ViewHandyMen", "view handy men"),
                    ("ManageHandyMen", "manage handy men"),
                    ("ViewDomesticStaff", "view domestic staff"),
                    ("ManageDomesticStaff", "manage domestic staff"),
                    ("ViewSecurityLog", "view security log"),
                    ("ManageSecurityLog", "manage security log"),
                    ("ViewEmergencyResponse", "view emergency response"),
                    ("ManageEmergencyResponse", "manage emergency response"),
                    ("ViewSecurityAlert", "view security alert"),
                    ("ManageSecurityAlert", "manage security alert"),
                    ("ViewClusterSettings", "view cluster settings"),
                    ("ManageClusterSettings", "manage cluster settings"),
                    ("ViewAuditLog", "view audit log"),
                    ("ManageAuditLog", "manage audit log"),
                    ("ViewSystemSettings", "view system settings"),
                    ("ManageSystemSettings", "manage system settings"),
                    ("ViewProfile", "view profile"),
                    ("ManageProfile", "manage profile"),
                    ("ViewSettings", "view settings"),
                    ("ManageSettings", "manage settings"),
                ],
                "default_permissions": [],
            },
            managers=[
                ("objects", accounts.models.users.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creation date"
                    ),
                ),
                (
                    "created_by",
                    models.UUIDField(
                        help_text="the Id of the ClustR account user who added this object.",
                        null=True,
                        verbose_name="created by",
                    ),
                ),
                (
                    "last_modified_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="last modified date"
                    ),
                ),
                (
                    "last_modified_by",
                    models.UUIDField(
                        help_text="the Id of the ClustR account user who last modified this object.",
                        null=True,
                        verbose_name="last modified by",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="UUID primary key",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("VISITOR_ARRIVAL", "Visitor Arrival"),
                            ("VISITOR_OVERSTAY", "Visitor Overstay"),
                            ("ANNOUNCEMENT", "Announcements"),
                            ("COMMENT_REPLY", "Comment Replies"),
                            ("ISSUE_STATUS_CHANGE", "Issue Status Changes"),
                            ("ISSUE_COMMENT", "Issue Comments"),
                            ("ISSUE_ASSIGNMENT", "Issue Assignment"),
                            ("POLL_NOTIFICATION", "Poll Notifications"),
                            ("EMERGENCY_ALERT", "Emergency Alerts"),
                            ("PAYMENT_REMINDER", "Payment Reminders"),
                            ("PAYMENT_CONFIRMATION", "Payment Confirmations"),
                            ("BILL_NOTIFICATION", "Bill Notifications"),
                            ("CHILD_EXIT", "Child Exit Notifications"),
                            ("CHILD_ENTRY", "Child Entry Notifications"),
                            ("CHILD_OVERDUE", "Child Overdue Notifications"),
                            ("EXIT_REQUEST", "Exit Request Notifications"),
                            ("MARKETPLACE_ACTIVITY", "Marketplace Activity"),
                            ("SHIFT_REMINDER", "Shift Reminders"),
                            ("TASK_ASSIGNMENT", "Task Assignment"),
                            ("TASK_DUE", "Task Due Reminders"),
                            ("MAINTENANCE_ALERT", "Maintenance Alerts"),
                        ],
                        max_length=50,
                        verbose_name="Notification Type",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("EMAIL", "Email"),
                            ("SMS", "SMS"),
                            ("PUSH", "Push Notification"),
                            ("IN_APP", "In-App Notification"),
                        ],
                        max_length=20,
                        verbose_name="Channel",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this notification type is enabled for this channel",
                        verbose_name="Enabled",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Preference",
                "verbose_name_plural": "Notification Preferences",
                "default_permissions": [],
            },
        ),
        migrations.CreateModel(
            name="PreviousPasswords",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="UUID primary key",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "passwords",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            max_length=128, verbose_name="password"
                        ),
                        default=list,
                        help_text="List of password hash of users old passwords",
                        null=True,
                        size=200,
                    ),
                ),
                (
                    "last_modified_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="last modified date"
                    ),
                ),
            ],
            options={
                "verbose_name": "previous passwords",
                "verbose_name_plural": "previous passwords",
                "default_permissions": [],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "group_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="auth.group",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creation date"
                    ),
                ),
                (
                    "created_by",
                    models.UUIDField(
                        help_text="the Id of the ClustR account user who added this object.",
                        null=True,
                        verbose_name="created by",
                    ),
                ),
                (
                    "last_modified_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="last modified date"
                    ),
                ),
                (
                    "last_modified_by",
                    models.UUIDField(
                        help_text="the Id of the ClustR account user who last modified this object.",
                        null=True,
                        verbose_name="last modified by",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Description of the role.",
                        verbose_name="description",
                    ),
                ),
            ],
            options={
                "verbose_name": "role",
                "verbose_name_plural": "roles",
                "ordering": ["-created_at"],
                "default_permissions": [],
            },
            bases=("auth.group", models.Model),
            managers=[
                ("objects", django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creation date"
                    ),
                ),
                (
                    "created_by",
                    models.UUIDField(
                        help_text="the Id of the ClustR account user who added this object.",
                        null=True,
                        verbose_name="created by",
                    ),
                ),
                (
                    "last_modified_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="last modified date"
                    ),
                ),
                (
                    "last_modified_by",
                    models.UUIDField(
                        help_text="the Id of the ClustR account user who last modified this object.",
                        null=True,
                        verbose_name="last modified by",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="UUID primary key",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "notification_preferences",
                    models.JSONField(
                        default=dict,
                        help_text="JSON object storing notification preferences by type and channel",
                        verbose_name="Notification Preferences",
                    ),
                ),
                (
                    "privacy_settings",
                    models.JSONField(
                        default=dict,
                        help_text="JSON object storing privacy preferences",
                        verbose_name="Privacy Settings",
                    ),
                ),
                (
                    "general_preferences",
                    models.JSONField(
                        default=dict,
                        help_text="JSON object storing general user preferences",
                        verbose_name="General Preferences",
                    ),
                ),
                (
                    "communication_preferences",
                    models.JSONField(
                        default=dict,
                        help_text="JSON object storing communication preferences",
                        verbose_name="Communication Preferences",
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="UTC",
                        help_text="User's preferred timezone",
                        max_length=50,
                        verbose_name="Timezone",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        default="en",
                        help_text="User's preferred language",
                        max_length=10,
                        verbose_name="Language",
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("light", "Light"),
                            ("dark", "Dark"),
                            ("auto", "Auto"),
                        ],
                        default="light",
                        help_text="User's preferred theme",
                        max_length=20,
                        verbose_name="Theme",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Settings",
                "verbose_name_plural": "User Settings",
                "default_permissions": [],
            },
        ),
        migrations.CreateModel(
            name="UserVerification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="UUID primary key",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                ("otp", models.CharField(max_length=5, null=True)),
                ("token", models.CharField(max_length=255, null=True)),
                (
                    "notification_event",
                    models.CharField(max_length=50, verbose_name="Notification event"),
                ),
                (
                    "requested_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Request date"
                    ),
                ),
                (
                    "is_used",
                    models.BooleanField(
                        default=False,
                        help_text="Has this token been used successfully?",
                        verbose_name="Is used?",
                    ),
                ),
            ],
            options={
                "verbose_name": "user verification",
                "ordering": ["-requested_at"],
            },
            bases=(
                models.Model,
                accounts.models.email_verification.BaseUserToken,
                core.common.code_generator.CodeGenerator,
            ),
        ),
    ]
