# Generated by Django 4.2.9 on 2024-08-11 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("common", "0001_initial"),
        ("accounts", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountuser",
            name="cluster",
            field=models.ForeignKey(
                help_text="The Estate that this user belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="residents",
                related_query_name="resident",
                to="common.cluster",
                verbose_name="cluster",
            ),
        ),
        migrations.AddField(
            model_name="accountuser",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AddField(
            model_name="accountuser",
            name="owner",
            field=models.ForeignKey(
                help_text="this is the primary",
                limit_choices_to={"is_owner": True},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subusers",
                related_query_name="subuser",
                to=settings.AUTH_USER_MODEL,
                verbose_name="primary account",
            ),
        ),
        migrations.AddField(
            model_name="accountuser",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(fields=["created_at"], name="accounts_ro_created_d4f417_idx"),
        ),
        migrations.AddConstraint(
            model_name="emailverification",
            constraint=models.CheckConstraint(
                check=models.Q(("otp__isnull", False), ("token__isnull", False), _negated=True),
                name="verification_key_otp_xor_token",
            ),
        ),
        migrations.AddIndex(
            model_name="accountuser",
            index=models.Index(fields=["name"], name="accounts_ac_name_862e8e_idx"),
        ),
        migrations.AddIndex(
            model_name="accountuser",
            index=models.Index(fields=["email_address"], name="accounts_ac_email_a_066e6d_idx"),
        ),
        migrations.AddIndex(
            model_name="accountuser",
            index=models.Index(fields=["date_joined"], name="accounts_ac_date_jo_4a81e7_idx"),
        ),
    ]
