# Generated by Django 5.2.4 on 2025-07-30 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountuser",
            name="clusters",
            field=models.ManyToManyField(
                help_text="Clusters that this user belongs to",
                related_name="users",
                related_query_name="user",
                to="common.cluster",
                verbose_name="clusters",
            ),
        ),
        migrations.AddField(
            model_name="accountuser",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AddField(
            model_name="accountuser",
            name="owner",
            field=models.ForeignKey(
                help_text="this is the primary",
                limit_choices_to={"is_owner": False},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subusers",
                related_query_name="subuser",
                to=settings.AUTH_USER_MODEL,
                verbose_name="primary account",
            ),
        ),
        migrations.AddField(
            model_name="accountuser",
            name="primary_cluster",
            field=models.ForeignKey(
                help_text="The primary cluster for this user",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="primary_users",
                related_query_name="primary_user",
                to="common.cluster",
                verbose_name="primary cluster",
            ),
        ),
        migrations.AddField(
            model_name="accountuser",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="cluster",
            field=models.ForeignKey(
                blank=True,
                help_text="Cluster-specific notification preference (optional)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification_preferences",
                to="common.cluster",
                verbose_name="Cluster",
            ),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification_preferences_detailed",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AddField(
            model_name="previouspasswords",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="previous_passwords",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="owner",
            field=models.ForeignKey(
                help_text="The admin this role belongs to",
                limit_choices_to={
                    "is_cluster_admin": True,
                    "is_owner": True,
                    "is_staff": False,
                },
                on_delete=django.db.models.deletion.CASCADE,
                related_name="roles",
                related_query_name="role",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Primary account",
            ),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="settings",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AddField(
            model_name="userverification",
            name="requested_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="verification_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="accountuser",
            index=models.Index(fields=["name"], name="accounts_ac_name_862e8e_idx"),
        ),
        migrations.AddIndex(
            model_name="accountuser",
            index=models.Index(
                fields=["email_address"], name="accounts_ac_email_a_066e6d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accountuser",
            index=models.Index(
                fields=["date_joined"], name="accounts_ac_date_jo_4a81e7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationpreference",
            index=models.Index(
                fields=["user", "notification_type"],
                name="accounts_no_user_id_ddff86_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationpreference",
            index=models.Index(
                fields=["user", "channel"], name="accounts_no_user_id_df27d2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationpreference",
            index=models.Index(
                fields=["cluster", "notification_type"],
                name="accounts_no_cluster_7dcc56_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="notificationpreference",
            unique_together={("user", "notification_type", "channel", "cluster")},
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(
                fields=["created_at"], name="accounts_ro_created_d4f417_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userverification",
            index=models.Index(
                fields=["requested_at"], name="accounts_us_request_f4494e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userverification",
            index=models.Index(
                fields=["requested_by"], name="accounts_us_request_07e7f0_idx"
            ),
        ),
    ]
