# Generated by Django 4.2.9 on 2024-08-16 05:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="emailverification",
            options={"ordering": ["-requested_at"], "verbose_name": "user verification"},
        ),
        migrations.RemoveConstraint(
            model_name="emailverification",
            name="verification_key_otp_xor_token",
        ),
        migrations.AlterField(
            model_name="accountuser",
            name="email_address",
            field=models.EmailField(max_length=100, unique=True, verbose_name="email address"),
        ),
        migrations.AlterField(
            model_name="accountuser",
            name="name",
            field=models.CharField(max_length=255, verbose_name="name of user"),
        ),
        migrations.AlterField(
            model_name="accountuser",
            name="owner",
            field=models.ForeignKey(
                help_text="this is the primary",
                limit_choices_to={"is_owner": False},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subusers",
                related_query_name="subuser",
                to=settings.AUTH_USER_MODEL,
                verbose_name="primary account",
            ),
        ),
        migrations.AlterField(
            model_name="accountuser",
            name="phone_number",
            field=models.CharField(
                editable=False,
                help_text="The phone number for this subscription in E.164 format. See details: https://www.twilio.com/docs/glossary/what-e164",
                max_length=16,
                validators=[
                    django.core.validators.MinLengthValidator(4),
                    django.core.validators.RegexValidator("^\\+[1-9]\\d{1,14}$"),
                ],
                verbose_name="phone number",
            ),
        ),
        migrations.AlterField(
            model_name="emailverification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("NEW_OWNER", "New Owner"),
                    ("NEW_SUBUSER_ACCOUNT_TO_SUBUSER", "New Subuser Account To Subuser"),
                    ("NEW_SUBUSER_ACCOUNT_TO_OWNER", "New Subuser Account To Owner"),
                    ("SUBUSER_ACCOUNT_UPDATE", "Subuser Account Update"),
                    ("ONBOARDING_OTP_PASSWORD_RESET", "Onboarding Otp Password Reset"),
                    ("ONBOARDING_TOKEN_PASSWORD_RESET", "Onboarding Token Password Reset"),
                    ("WEB_TOKEN_PASSWORD_RESET", "Web Token Password Reset"),
                    ("OTP_PASSWORD_RESET", "Otp Password Reset"),
                    ("RESEND_OTP", "Resend Otp"),
                    ("RESEND_WEB_TOKEN", "Resend Web Token"),
                    ("PASSWORD_CHANGED", "Password Changed"),
                    ("IMPORT_SUCCESS", "Import Success"),
                    ("EXPORT_SUCCESS", "Export Success"),
                ],
                max_length=50,
                verbose_name="Notification type",
            ),
        ),
        migrations.AddIndex(
            model_name="emailverification",
            index=models.Index(fields=["requested_at"], name="accounts_em_request_273911_idx"),
        ),
        migrations.AddIndex(
            model_name="emailverification",
            index=models.Index(fields=["requested_by"], name="accounts_em_request_e2e894_idx"),
        ),
    ]
