# Generated by Django 5.2.4 on 2025-07-31 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userverification",
            options={
                "default_permissions": [],
                "ordering": ["-requested_at"],
                "verbose_name": "user verification",
            },
        ),
    ]
