# Generated by Django 4.2.9 on 2024-08-16 05:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_emailverification_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountuser",
            name="property_owner",
            field=models.BooleanField(default=False, verbose_name="Property owner"),
        ),
    ]
