# Generated by Django 4.2.9 on 2024-08-17 06:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_accountuser_property_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailverification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("NEW_ADMIN_ONBOARDING", "New Admin Onboarding"),
                    ("NEW_SUBUSER_ACCOUNT_TO_SUBUSER", "New Subuser Account To Subuser"),
                    ("NEW_SUBUSER_ACCOUNT_TO_OWNER", "New Subuser Account To Owner"),
                    ("SUBUSER_ACCOUNT_UPDATE", "Subuser Account Update"),
                    ("ONBOARDING_OTP_PASSWORD_RESET", "Onboarding Otp Password Reset"),
                    ("ONBOARDING_TOKEN_PASSWORD_RESET", "Onboarding Token Password Reset"),
                    ("WEB_TOKEN_PASSWORD_RESET", "Web Token Password Reset"),
                    ("OTP_PASSWORD_RESET", "Otp Password Reset"),
                    ("RESEND_OTP", "Resend Otp"),
                    ("RESEND_WEB_TOKEN", "Resend Web Token"),
                    ("PASSWORD_CHANGED", "Password Changed"),
                    ("IMPORT_SUCCESS", "Import Success"),
                    ("EXPORT_SUCCESS", "Export Success"),
                ],
                max_length=50,
                verbose_name="Notification type",
            ),
        ),
    ]
