# Generated by Django 5.2.5 on 2026-01-07 08:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_accountuser_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmergencyContact",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creation date"
                    ),
                ),
                (
                    "created_by",
                    models.UUIDField(
                        help_text="the Id of the ClustR account user who added this object.",
                        null=True,
                        verbose_name="created by",
                    ),
                ),
                (
                    "last_modified_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="last modified date"
                    ),
                ),
                (
                    "last_modified_by",
                    models.UUIDField(
                        help_text="the Id of the ClustR account user who last modified this object.",
                        null=True,
                        verbose_name="last modified by",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="UUID primary key",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the emergency contact",
                        max_length=255,
                        verbose_name="contact name",
                    ),
                ),
                (
                    "relationship",
                    models.CharField(
                        help_text="Relationship to the user (e.g., spouse, parent, friend)",
                        max_length=100,
                        verbose_name="relationship",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        help_text="Phone number of the emergency contact in E.164 format",
                        max_length=16,
                        verbose_name="phone number",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Email address of the emergency contact",
                        max_length=100,
                        null=True,
                        verbose_name="email address",
                    ),
                ),
                (
                    "contact_type",
                    models.CharField(
                        choices=[
                            ("HEALTH", "Health Emergency"),
                            ("SECURITY", "Security Emergency"),
                            ("FIRE", "Fire Emergency"),
                            ("DOMESTIC", "Domestic Violence"),
                            ("OTHER", "Other Emergency"),
                        ],
                        default="OTHER",
                        help_text="Type of emergency this contact should be notified for",
                        max_length=20,
                        verbose_name="contact type",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is the primary emergency contact",
                        verbose_name="is primary contact",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user this emergency contact belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emergency_contacts",
                        related_query_name="emergency_contact",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "emergency contact",
                "verbose_name_plural": "emergency contacts",
                "ordering": ["-is_primary", "name"],
                "default_permissions": [],
                "indexes": [
                    models.Index(
                        fields=["user"], name="accounts_em_user_id_4e5240_idx"
                    ),
                    models.Index(
                        fields=["contact_type"], name="accounts_em_contact_aa7dab_idx"
                    ),
                ],
            },
        ),
    ]
