# Generated by Django 4.2.9 on 2024-08-22 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0004_remove_cluster_admin_cluster_owner_id"),
        ("accounts", "0005_alter_emailverification_notification_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountuser",
            name="cluster",
            field=models.ForeignKey(
                help_text="The Estate that this user belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                related_query_name="member",
                to="common.cluster",
                verbose_name="cluster",
            ),
        ),
    ]
