"""
Django settings for clustr project.

Generated by 'django-admin startproject' using Django 3.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from datetime import timedelta
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve(strict=True).parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "#zeq)d@+g5(i3it%0ehxv$+v*#czxw6w)s$5idb_om)1dtq-9!"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "channels",
    "rest_framework",
    "drf_yasg",
    "corsheaders",
    "accounts",
    "members",
    "management",
    "core.common",
    "core.data_exchange",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "core.common.middleware.request_middleware.RequestMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "core.common.middleware.jwt_middleware.JWTAuthenticationMiddleware",
    "core.common.middleware.cluster_middleware.ClusterContextMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"
ASGI_APPLICATION = "config.asgi.application"


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

AUTH_USER_MODEL = "accounts.AccountUser"

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME", "clustr"),
        "USER": os.getenv("DB_USER", "postgres"),
        "PASSWORD": os.getenv("DB_PASSWORD", "skybrow77"),
        "HOST": os.getenv("DB_HOST", "localhost"),
        "PORT": os.getenv("DB_PORT", "5432"),
        "CONN_MAX_AGE": 600,
        "OPTIONS": {
            "connect_timeout": 10,
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Password hashers - MD5 for development speed only
PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher",
] if not DEBUG else [
    "django.contrib.auth.hashers.MD5PasswordHasher",
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = "/static/"

# CORS settings
CORS_ALLOW_ALL_ORIGINS = DEBUG
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]
CORS_ALLOW_CREDENTIALS = True

# Session settings
SESSION_ENGINE = "django.contrib.sessions.backends.cached_db"
SESSION_CACHE_ALIAS = "default"

# REST Framework settings
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "accounts.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
    # "EXCEPTION_HANDLER": "core.common.exception_handlers.custom_exception_handler",
}

# JWT settings
JWT_SECRET_KEY = SECRET_KEY  # Use the same secret key for JWT
JWT_ACCESS_TOKEN_LIFETIME_HOURS = 1
JWT_REFRESH_TOKEN_LIFETIME_DAYS = 7
JWT_EXTENDED_TOKEN_LIFETIME = timedelta(hours=6)


REFRESH_TOKEN_LIFETIME = timedelta(days=1)
REFRESH_TOKEN_LIFETIME_WITH_REMEMBER_ME = timedelta(days=7)

# File storage settings
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default file storage (local for development)
DEFAULT_FILE_STORAGE = "django.core.files.storage.FileSystemStorage"

# Logging configuration
os.makedirs(os.path.join(BASE_DIR, "logs"), exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "simple": {
            "format": "{asctime} {levelname} {message}",
            "style": "{",
        },
        "detailed": {
            "format": "{asctime} {levelname} {name} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
            "level": "DEBUG" if DEBUG else "INFO",
        },
        "file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.path.join(BASE_DIR, "logs", "app.log"),
            "maxBytes": 10 * 1024 * 1024,
            "backupCount": 3,
            "formatter": "detailed",
            "level": "INFO",
        },
    },
    "loggers": {
        "clustr": {
            "handlers": ["console", "file"],
            "level": "DEBUG" if DEBUG else "INFO",
            "propagate": False,
        },
        "django": {
            "handlers": ["console"],
            "level": "INFO" if DEBUG else "WARNING",
        },
        "django.request": {
            "handlers": ["console", "file"],
            "level": "ERROR",
            "propagate": False,
        },
    },
}

# Channels configuration
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [os.getenv("REDIS_URL", "redis://localhost:6379/1")],
        },
    },
}

# Cache settings
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "clustr-cache",
        "OPTIONS": {
            "MAX_ENTRIES": 1000,
        },
    }
}

# Celery settings
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "redis://localhost:6379/0")
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", "redis://localhost:6379/0")
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE

# Celery Beat schedule
CELERY_BEAT_SCHEDULE = {
    "detect-visitor-overstays-every-hour": {
        "task": "detect_visitor_overstays",
        "schedule": 3600.0,  # Every hour
    },
    "update-invitation-statuses-daily": {
        "task": "update_invitation_statuses",
        "schedule": 86400.0,  # Every day
    },
    "check-missed-shifts-every-15-minutes": {
        "task": "check_missed_shifts",
        "schedule": 900.0,  # Every 15 minutes
    },
    "send-shift-reminders-hourly": {
        "task": "send_shift_reminders",
        "schedule": 3600.0,  # Every hour
    },
    "spawn-check-task-deadlines-daily": {
        "task": "spawn_check_task_deadlines",
        "schedule": 86400.0,  # Every day
    },
    "spawn-process-maintenance-schedules-daily": {
        "task": "spawn_process_maintenance_schedules",
        "schedule": 86400.0,  # Every day
    },
    "check-overdue-children-every-15-minutes": {
        "task": "check_overdue_children",
        "schedule": 900.0,  # Every 15 minutes
    },
    "expire-old-exit-requests-hourly": {
        "task": "expire_old_exit_requests",
        "schedule": 3600.0,  # Every hour
    },
    "send-exit-request-reminders-hourly": {
        "task": "send_exit_request_reminders",
        "schedule": 3600.0,  # Every hour
    },
    "spawn-process-recurring-payments-daily": {
        "task": "spawn_process_recurring_payments",
        "schedule": 86400.0,  # Every day
    },
    "spawn-send-recurring-payment-reminders-daily": {
        "task": "spawn_send_recurring_payment_reminders",
        "schedule": 86400.0,  # Every day
    },
    "spawn-check-overdue-bills-daily": {
        "task": "spawn_check_overdue_bills",
        "schedule": 86400.0,  # Every day
    },
    "spawn-send-bill-reminders-daily": {
        "task": "spawn_send_bill_reminders",
        "schedule": 86400.0,  # Every day
    },
    "retry-failed-utility-payments-daily": {
        "task": "retry_failed_utility_payments",
        "schedule": 86400.0,  # Every day
    },
}
